services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    image: custom-jenkins-devops:latest
    container_name: jenkins-devops
    ports:
      - "8088:8080"
      - "50000:50000"
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    volumes:
      - jenkins_data:/var/jenkins_home
      - ./init-scripts:/usr/share/jenkins/ref/init.groovy.d
      - ../deployments:/host_deployments
    restart: unless-stopped

volumes:
  jenkins_data:
